/* Search function */

USE --Db name

DECLARE @tblis AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @tblwas AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @tblwillbe AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @fieldis AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @fieldwas AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @fieldwillbe AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’
DECLARE @schema AS nvarchar(88) = '%%'--UPDATE AS NEEDED HERE WITHIN THE ‘’

SELECT DISTINCT TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	IS_NULLABLE,
	CHARACTER_MAXIMUM_LENGTH,
	COLLATION_NAME
FROM INFORMATION_SCHEMA.COLUMNS WITH (NOLOCK) --Minimize impact on production staff
WHERE TABLE_NAME LIKE @tblis
	AND COLUMN_NAME LIKE @fieldis
	AND TABLE_NAME IN (
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME LIKE @tblwas
			AND COLUMN_NAME LIKE @fieldwas
	)
	AND TABLE_NAME IN (
		SELECT TABLE_NAME
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME LIKE @tblwillbe
			AND COLUMN_NAME LIKE @fieldwillbe
	)
	AND TABLE_SCHEMA LIKE @schema
ORDER BY TABLE_NAME, COLUMN_NAME ASC